name: deploy all

on:
  push:
    branches: master

jobs:
  download: 
    runs-on: [self-hosted, linux, x64]  
    steps:  
    - name: download new changes
      uses: actions/checkout@v2
  build_web:
    runs-on: [self-hosted, linux, x64]  
    needs: download
    steps:  
    - name: install dependencies
      run: cd soa-web-app/vue-web; npm install
    - name: build vue web
      run: cd soa-web-app/vue-web; npm run build
    - name: create final location directory
      run: mkdir soa-web-app/node-server/static
    - name: copy web to final location
      run: mv ./soa-web-app/vue-web/dist/* ./soa-web-app/node-server/static/
  build_web_server:
    runs-on: [self-hosted, linux, x64]  
    needs: download
    steps:  
    - name: install dependencies
      run: cd soa-web-app/node-server; npm install
    - name: build node server
      run: cd soa-web-app/node-server; npm run build
  restart:
    runs-on: [self-hosted, linux, x64]
    needs: [build_web, build_web_server]
    steps:
    - name: restarting pm2 services
      run: /usr/local/bin/pm2 restart all
